[package]
name = "trivial-strace"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0.83"
bindgen = "0.69.2"

[dependencies]
nix = {version = "0.27.1", features = ["process", "signal", "uio"]}
